### ISSUE TITLE
Detect fits instrument / help text hidden behind boxes in gooey

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/astro_scripts#14]
It could be easier for quick excecution if plot_fits.py detected the instrument type in the header instead of the drop down list.

Having it default to ARES I have missed changing it to CRIRES in a hurry and therefore get the error.

Traceback (most recent call last):
  File "..Repos/astro_scripts/plot_fits.py", line 566, in <module>
    main(fname, **opts)
  File "..Repos/astro_scripts/plot_fits.py", line 334, in main
    w = get_wavelength(hdr)
UnboundLocalError: local variable 'hdr' referenced before assignment

The CRIRES header has a value INSTRUME= 'CRIRES  ' (I assume ARES would be similar), which would be simple enough to check for example something like ... 

if hdr["INSTRUME"] is "CRIRES ":
    do this    
elif hdr["INSTRUMENT"] is "ARES":
    do that

Also a bug:
The help text gets hidden behind the Gooey boxes for model and lines. Also a spelling mistake in model help.

**Comment by DanielAndreasen** [comment]
Hi Jason,

Thanks for opening the issue. To look at the instrument is a clever idea. The ARES option, is actually just a 1D spectrum with the wavelength information stored in the header. ARES is a software for measuring EW and not an instrument, but I guess I can set that keyword, or at least look for it.

As far as goes for the help text hidden by the Gooey boxes, this is also a problem I've encountered. We probably have to ask the team to do something about this, or find a better solution.  
Anyway, you can always read the help by running: `python plot_fits.py --ignore-gooey -h` or look at the source code.
